[package]
name = "rust-perceptron"
version = "0.1.0"
authors = ["shirishph <shirish.ph@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
